server:
  version: v1
  port: 8001
  read-timeout: 10                # 读取等待时间，单位: 秒
  write-timeout: 20               # 写等待时间，单位: 秒
log:
  info:
    file: ./logs/info/info.log    # warn、debug、info日志文件存放目录
    max-size: 10                  # 文件大小限制,单位MB
    max-backups: 10               # 最大保留日志文件数量
    max-age: 30                   # 日志文件保留天数
    compress: true                # 是否压缩处理
  err:
    file: ./logs/err/err.log      # 日志文件存放目录
    max-size: 10                  # 文件大小限制,单位MB
    max-backups: 5                # 最大保留日志文件数量
    max-age: 30                   # 日志文件保留天数
    compress: true                # 是否压缩处理
redis:
  network: tcp
  host: 127.0.0.1
  port: 6379
  max-idle: 1000                  # 连接池最多空闲连接数
  max-active: 2000                # 连接池最多连接数
  idle-timeout: 60                # 经过该时间，空闲连接将被回收
kafka:
  brokers: "127.0.0.1:9092 127.0.0.1:9093 127.0.0.1:9094"
discovery:
  server:
    ip: 127.0.0.1  # nacos ip
    port: 8848
  instance:
    ip: 127.0.0.1
    name: spike.buy
    weight: 10
    healthy: true
    ephemeral: true
    cluster-name: spike-buy
    group-name: spike-buy-group
